/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE frasi-hBaseService PLEASE EDIT ../frasi-h.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { FrasiH } from '../../domain/movarisch_db/frasi-h';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../FrasiH.service.ts
 */

/*
 * SCHEMA DB FrasiH
 *
	{
		Codice: {
			type: 'String',
			required : true
		},
		Descrizione: {
			type: 'String',
			required : true
		},
		Punteggio: {
			type: 'Decimal',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		FrasiH: [{
			type: Schema.ObjectId,
			ref : "Sostanza"
		}],
	}
 *
 */
@Injectable()
export class FrasiHBaseService {

    contextUrl: string = environment.endpoint + '/frasih';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * FrasiHService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: FrasiH): Observable<FrasiH> {
        return this.http
            .post<FrasiH>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * FrasiHService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * FrasiHService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id FrasiH
    *   @returns FrasiH
    *
    */
    get(id: string): Observable<FrasiH> {
        return this.http
            .get<FrasiH>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * FrasiHService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<FrasiH[]> {
        return this.http
            .get<FrasiH[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * FrasiHService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: FrasiH): Observable<FrasiH> {
        return this.http
            .post<FrasiH>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
