/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE miscelanonpericolosaBaseService PLEASE EDIT ../miscelanonpericolosa.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Miscelanonpericolosa } from '../../domain/movarisch_db/miscelanonpericolosa';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Miscelanonpericolosa.service.ts
 */

/*
 * SCHEMA DB Miscelanonpericolosa
 *
	{
		Nome: {
			type: 'String',
			required : true
		},
		Score: {
			type: 'Decimal'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Sostanza: [{
			type: Schema.ObjectId,
			ref : "Miscelanonpericolosa"
		}],
	}
 *
 */
@Injectable()
export class MiscelanonpericolosaBaseService {

    contextUrl: string = environment.endpoint + '/miscelanonpericolosa';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * MiscelanonpericolosaService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Miscelanonpericolosa): Observable<Miscelanonpericolosa> {
        return this.http
            .post<Miscelanonpericolosa>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * MiscelanonpericolosaService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * MiscelanonpericolosaService.findByNome
    *   @description CRUD ACTION findByNome
    *   @param Objectid key Id of the resource Nome to search
    *
    */
    findByNome(id: string): Observable<Miscelanonpericolosa[]> {
        return this.http
            .get<Miscelanonpericolosa[]>(this.contextUrl + '/findByNome/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * MiscelanonpericolosaService.findBySostanza
    *   @description CRUD ACTION findBySostanza
    *   @param Objectid key Id of the resource Sostanza to search
    *
    */
    findBySostanza(id: string): Observable<Miscelanonpericolosa[]> {
        return this.http
            .get<Miscelanonpericolosa[]>(this.contextUrl + '/findBySostanza/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * MiscelanonpericolosaService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Miscelanonpericolosa> {
        return this.http
            .get<Miscelanonpericolosa>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * MiscelanonpericolosaService.getSostanza
    *   @description CRUD ACTION getSostanza
    *   @param Objectid id ID of Miscelanonpericolosa from Sostanza
    *
    */
    getSostanza(id: string): Observable<any[]> {
        return this.http
            .get<any[]>(this.contextUrl + '/' + id + 'getSostanza')
            .pipe(
                map(response => response)
            );
     }

    /**
    * MiscelanonpericolosaService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Miscelanonpericolosa[]> {
        return this.http
            .get<Miscelanonpericolosa[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * MiscelanonpericolosaService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Miscelanonpericolosa): Observable<Miscelanonpericolosa> {
        return this.http
            .post<Miscelanonpericolosa>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
